# Supabase configuration file (generated for jobsAutomation-api)
# Docs: https://supabase.com/docs/reference/cli/config

project_id = "jobsautomation-api"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083

[functions.on-job-changed]
verify_jwt = false
import_map = "./import_map.json"
