// ============================================================
//  Supabase client + run-status helpers for Azure Functions.
//  Uses the service-role key (server-side only) so Functions can
//  update pipeline_runs and jobs status on behalf of users.
// ============================================================

import { createClient, SupabaseClient } from "@supabase/supabase-js";

let _client: SupabaseClient | null = null;

export function getSupabaseClient(): SupabaseClient {
  if (_client) return _client;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) {
    throw new Error(
      "SUPABASE_URL / SUPABASE_SERVICE_KEY not set (see local.settings.json / App Settings)",
    );
  }
  _client = createClient(url, key, { auth: { persistSession: false } });
  return _client;
}

// ── pipeline_runs status transitions ────────────────────────────────────────

export type RunStatus =
  | "queued"
  | "scraping"
  | "processing"
  | "completed"
  | "failed"
  | "retrying";

/**
 * Update a pipeline_run row. Only non-undefined fields are patched.
 * Returns false on error (caller logs).
 */
export async function updateRun(
  runId: string,
  patch: Partial<PipelineRunPatch>,
): Promise<boolean> {
  const supabase = getSupabaseClient();
  const { error } = await supabase
    .from("pipeline_runs")
    .update(patch)
    .eq("id", runId);
  if (error) {
    console.error(`[supabase] updateRun(${runId}) failed: ${error.message}`);
    return false;
  }
  return true;
}

interface PipelineRunPatch {
  status: RunStatus;
  total_jobs: number;
  processed_jobs: number;
  failed_jobs: number;
  fit_jobs: number;
  azure_run_id: string;
  last_error: string;
  retry_count: number;
  started_at: string;
  completed_at: string;
}

/** Mark a run as queued (initial state). */
export async function markRunQueued(
  runId: string,
  azureRunId: string,
): Promise<void> {
  await updateRun(runId, { status: "queued", azure_run_id: azureRunId });
}

/** Mark a run as scraping (scraper worker started). */
export async function markRunScraping(runId: string): Promise<void> {
  await updateRun(runId, {
    status: "scraping",
    started_at: new Date().toISOString(),
  });
}

/** Mark a run as processing (jobs fanning out). */
export async function markRunProcessing(runId: string): Promise<void> {
  await updateRun(runId, { status: "processing" });
}

/** Mark a run completed (all jobs done). */
export async function markRunCompleted(
  runId: string,
  totals: { total: number; processed: number; failed: number; fit: number },
): Promise<void> {
  await updateRun(runId, {
    status: "completed",
    total_jobs: totals.total,
    processed_jobs: totals.processed,
    failed_jobs: totals.failed,
    fit_jobs: totals.fit,
    completed_at: new Date().toISOString(),
  });
}

/** Mark a run failed with an error message. */
export async function markRunFailed(
  runId: string,
  error: string,
): Promise<void> {
  await updateRun(runId, {
    status: "failed",
    last_error: String(error).slice(0, 2000),
    completed_at: new Date().toISOString(),
  });
}

/** Increment retry_count and set status retrying. */
export async function markRunRetrying(
  runId: string,
  error: string,
): Promise<void> {
  const supabase = getSupabaseClient();
  // Read current retry_count then increment (simplified; fine for our throughput)
  const { data } = await supabase
    .from("pipeline_runs")
    .select("retry_count")
    .eq("id", runId)
    .maybeSingle();
  const count = (data?.retry_count ?? 0) + 1;
  await updateRun(runId, {
    status: "retrying",
    retry_count: count,
    last_error: String(error).slice(0, 2000),
  });
}

// ── per-job status helpers ──────────────────────────────────────────────────

export async function upsertJob(
  row: Record<string, unknown>,
): Promise<boolean> {
  const supabase = getSupabaseClient();
  const { error } = await supabase.from("jobs").upsert(row, {
    onConflict: "url,scraped_date,user_id",
  });
  if (error) {
    console.error(`[supabase] upsertJob failed: ${error.message}`);
    return false;
  }
  return true;
}

export async function updateJobStatus(
  jobId: string,
  status: string,
  patch: Record<string, unknown> = {},
): Promise<boolean> {
  const supabase = getSupabaseClient();
  const { error } = await supabase
    .from("jobs")
    .update({ status, ...patch })
    .eq("id", jobId);
  if (error) {
    console.error(
      `[supabase] updateJobStatus(${jobId}) failed: ${error.message}`,
    );
    return false;
  }
  return true;
}

/**
 * Update a job's status by its unique URL (safer than id — the
 * Service Bus message carries a random jobId, NOT the DB row id,
 * which is generated by Supabase). The scraper worker pre-inserts
 * the row using the same (url, scraped_date, user_id) unique key,
 * so matching by URL is reliable. Returns the matched DB row id,
 * or null when no row matched yet.
 */
export async function updateJobStatusByUrl(
  url: string,
  status: string,
  patch: Record<string, unknown> = {},
): Promise<string | null> {
  const supabase = getSupabaseClient();

  // 1. Find the actual row (created by the scraper's pre-insert)
  const { data: row, error: findErr } = await supabase
    .from("jobs")
    .select("id")
    .eq("url", url)
    .maybeSingle();

  if (findErr) {
    console.error(`[supabase] findJobByUrl(${url}) failed: ${findErr.message}`);
    return null;
  }
  if (!row) return null; // no pre-inserted row yet — upsert will create it

  // 2. Update status on the real row id
  const { error } = await supabase
    .from("jobs")
    .update({ status, ...patch })
    .eq("id", row.id);
  if (error) {
    console.error(
      `[supabase] updateJobStatusByUrl(${url}) failed: ${error.message}`,
    );
    return null;
  }
  return row.id as string;
}

/**
 * Set jobs.resume_status (none | ready_to_build | building | completed | failed)
 * plus optional patch (resume_url, resume_error, timestamps).
 * Returns the job's DB row id, or null when no row matched.
 */
export async function updateJobResumeStatus(
  jobId: string,
  resumeStatus: string,
  patch: Record<string, unknown> = {},
): Promise<boolean> {
  const supabase = getSupabaseClient();
  const { error } = await supabase
    .from("jobs")
    .update({ resume_status: resumeStatus, ...patch })
    .eq("id", jobId);
  if (error) {
    console.error(
      `[supabase] updateJobResumeStatus(${jobId}) failed: ${error.message}`,
    );
    return false;
  }
  return true;
}
