// ============================================================
//  Shared types for the Azure Functions layer.
//  Mirrors src/pipeline/types.ts in the repo root so the
//  serverless functions stay consistent with the legacy app.
// ============================================================

/** A job listing discovered by a scraper. */
export interface ScrapedJob {
  source?: string;
  title: string;
  company: string;
  location: string;
  salary?: string;
  postedDate?: string;
  url: string;
  description?: string;
  /** Pre-fetched full HTML (Indeed batch etc.) */
  rawDetailHtml?: string;
  /** Board key this job came from (jobsdb, ctgoodjobs, indeed, offertoday) */
  board?: string;

  // ── Normalized quality contract (stamped by normalize.applyNormalized) ──
  // These fields carry the normalized data from the scraper worker through
  // Service Bus to the job processor, so the frontend gets a CONSISTENT
  // contract across every board (not just the raw board-shaped fields above).
  /** Structured salary { display, min, max, period, currency, confidence }. */
  _normSalary?: {
    display: string | null;
    min: number | null;
    max: number | null;
    period: "month" | "year" | "hour" | "day" | null;
    currency: string | null;
    confidence: "high" | "medium" | "low" | "none";
  };
  /** Data-quality signals (completeness + presence flags). */
  _normDataQuality?: {
    completeness: number;
    hasSalary: boolean;
    hasDescription: boolean;
    hasPostedDate: boolean;
    hasLocation: boolean;
  };
  /** Deterministic board|url hash — stable id across runs. */
  _normJobId?: string;
  /** ISO YYYY-MM-DD posted date (normalized from relative strings). */
  _normPostedDate?: string;
}

/** Parsed job detail (from enrichment). */
export interface JobDetail {
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
  skills: string[];
  employmentType?: string;
  experienceLevel?: string;
  aboutCompany?: string;
  rawDescription: string;
}

export type EnrichedJob = ScrapedJob & { jobDetail: JobDetail };

export interface FitAnalysis {
  fit: boolean;
  score: number;
  reasons: string[];
  coverLetter?: string;
  expectedSalary?: string;
}

export type AnalysedJob = EnrichedJob & { fitAnalysis?: FitAnalysis };

/** Resume profile extracted once, reused across jobs (saves ~75% tokens). */
export interface ResumeProfile {
  yearsOfExperience: number;
  currentRole: string;
  keySkills: string[];
  education: string;
  industries: string[];
  languages: string[];
  summary: string;
}

// ── Service Bus message payloads ────────────────────────────────────────────

/** Message enqueued on `scrape-requests` by the scrape HTTP trigger. */
export interface ScrapeRequestMessage {
  type: "scrape";
  runId: string; // pipeline_runs.id (UUID)
  userId: string;
  keyword: string;
  pages: number;
  boards: string[];
  countryCode?: string;
}

/** Message enqueued on `jobs` by the scraper worker, one per listing. */
export interface JobMessage {
  type: "process-job";
  jobId: string; // unique id generated by scraper (url hash) — used for idempotency
  runId: string; // pipeline_runs.id
  userId: string;
  board: string;
  scrapedJob: ScrapedJob;
  keyword: string;
  scrapedDate: string; // YYYY-MM-DD
}

/** Message enqueued on `resume-builds` — build a tailored resume for a fit job. */
export interface ResumeBuildMessage {
  type: "build-resume";
  runId: string; // pipeline_runs.id
  userId: string;
  jobId: string; // the jobs row id (UUID)
  jobTitle: string;
  company: string;
  jobUrl: string;
  rawDescription: string;
  fitScore: number;
  fitReasons: string[];
  originalResumeText: string; // text extracted from the user's uploaded resume
}

// ── Supabase row shapes (subset) ────────────────────────────────────────────

export interface PipelineRunRow {
  id: string;
  user_id: string | null;
  keyword: string;
  search_key: string;
  boards: string[];
  country_code: string | null;
  status:
    | "queued"
    | "scraping"
    | "processing"
    | "completed"
    | "failed"
    | "retrying";
  total_jobs: number;
  processed_jobs: number;
  failed_jobs: number;
  fit_jobs: number;
  azure_run_id: string | null;
  last_error: string | null;
  retry_count: number;
  started_at: string | null;
  completed_at: string | null;
}

export interface JobRow {
  id: string;
  title: string;
  company: string;
  location: string | null;
  salary: string | null;
  salary_min: number | null;
  salary_max: number | null;
  salary_period: string | null;
  salary_currency: string | null;
  salary_confidence: string | null;
  data_quality: {
    completeness: number;
    has_salary: boolean;
    has_description: boolean;
    has_posted_date: boolean;
    has_location: boolean;
  } | null;
  posted_date: string | null;
  url: string;
  short_description: string | null;
  keyword: string;
  search_key: string;
  scraped_date: string;
  responsibilities: string[];
  requirements: string[];
  benefits: string[];
  skills: string[];
  employment_type: string | null;
  experience_level: string | null;
  about_company: string | null;
  raw_description: string | null;
  fit: boolean | null;
  fit_score: number | null;
  fit_reasons: string[];
  cover_letter: string | null;
  expected_salary: string | null;
  user_id: string | null;
  status: string;
  pipeline_run_id: string | null;
  board: string | null;
  resume_status: string | null;
  resume_url: string | null;
  resume_file_name: string | null;
  resume_error: string | null;
}

/** A generated tailored resume — links user_id + job_id → resume_url. */
export interface GeneratedResumeRow {
  id: string;
  user_id: string;
  job_id: string;
  status: "queued" | "building" | "completed" | "failed";
  resume_url: string | null;
  file_name: string | null;
  error: string | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
}
